name       : python-isodate
version    : 0.5.4
release    : 1
source     :
    - https://pypi.python.org/packages/f4/5b/fe03d46ced80639b7be9285492dc8ce069b841c0cebe5baacdd9b090b164/isodate-0.5.4.tar.gz : 42105c41d037246dc1987e36d96f3752ffd5c0c24834dd12e4fdbe1e79544e31
license    : BSD-3-Clause
component  : programming.python
summary    : An ISO 8601 date/time/duration parser and formatter
description: |
    An ISO 8601 date/time/duration parser and formatter
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
