name       : python-isodate
version    : 0.6.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/i/isodate/isodate-0.6.1.tar.gz : 48c5881de7e8b0a0d648cb024c8062dc84e7b840ed81e864c7614fd3c127bde9
license    : BSD-3-Clause
component  : programming.python
summary    : An ISO 8601 date/time/duration parser and formatter
description: |
    This module implements ISO 8601 date, time and duration parsing. The implementation follows ISO8601:2004 standard, and implements only date/time representations mentioned in the standard. If something is not mentioned there, then it is treated as non existent, and not as an allowed option.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
