name       : python-isodate
version    : 0.6.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/i/isodate/isodate-0.6.0.tar.gz : 2e364a3d5759479cdb2d37cce6b9376ea504db2ff90252a2e5b7cc89cc9ff2d8
license    : BSD-3-Clause
component  : programming.python
summary    : An ISO 8601 date/time/duration parser and formatter
description: |
    This module implements ISO 8601 date, time and duration parsing. The implementation follows ISO8601:2004 standard, and implements only date/time representations mentioned in the standard. If something is not mentioned there, then it is treated as non existent, and not as an allowed option.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
